CREATE DATABASE QLHANGHOA
USE QLHANGHOA

CREATE TABLE NHA_CUNG_CAP 
(
    MANCC VARCHAR(10) CONSTRAINT PK_NCC PRIMARY KEY,
    TENNCC NVARCHAR(100) NOT NULL,
    SDT CHAR(10) NOT NULL CONSTRAINT UQ_SDTNCC UNIQUE, 
    CONSTRAINT CHK_SDT_NCC CHECK (LEN(SDT) = 10 AND SDT NOT LIKE '%[^0-9]%'),
    DIACHI NVARCHAR(100) NOT NULL
)

CREATE TABLE HANG_HOA 
(
    MAHH VARCHAR(10) CONSTRAINT PK_HH PRIMARY KEY,
    TENHANG NVARCHAR(100) NOT NULL CONSTRAINT UQ_TENHH UNIQUE,
    DVT NVARCHAR(10) NOT NULL,
    TONKHO INT CONSTRAINT CHK_TONKHO CHECK (TONKHO >= 0)
)

CREATE TABLE KHACH_HANG 
(
    MAKH VARCHAR(10) CONSTRAINT PK_KH PRIMARY KEY,
    TENKH NVARCHAR(100) NOT NULL,
    SDT CHAR(10), 
    CONSTRAINT CHK_SDT_KH CHECK ((LEN(SDT) = 10 AND SDT NOT LIKE '%[^0-9]%')),
    DIACHI NVARCHAR(100) 
)

CREATE TABLE NHAN_VIEN 
(
    MANV VARCHAR(10) CONSTRAINT PK_NV PRIMARY KEY,
    TENNV NVARCHAR(100) NOT NULL,
    SDT CHAR(10) NOT NULL CONSTRAINT UQ_SDTNV UNIQUE, 
    CONSTRAINT CHK_SDT_NV CHECK (LEN(SDT) = 10 AND SDT NOT LIKE '%[^0-9]%'),
    DIACHI NVARCHAR(100) NOT NULL 
)

CREATE TABLE NHAP 
(
    MAHDNHAP VARCHAR(20) CONSTRAINT PK_NHAP PRIMARY KEY, 
    KYHIEU VARCHAR(10) NOT NULL, 
    SOHD INT NOT NULL, 
    CONSTRAINT UQ_KH_SOHD_NHAP UNIQUE (SOHD, KYHIEU),
    THUEVAT DECIMAL(5,2) NOT NULL CONSTRAINT CHK_THUENHAP CHECK (THUEVAT BETWEEN 0 AND 10),
    TONGCONG MONEY CONSTRAINT CHK_TONGCONGNHAP CHECK (TONGCONG >= 0),
    TONGTIEN MONEY CONSTRAINT CHK_TONGTIENNHAP CHECK (TONGTIEN >= 0),
    HTTT VARCHAR(2) CONSTRAINT CHK_HTTTNHAP CHECK (HTTT IN ('TM', 'CK')),
    NGAYHD DATETIME NOT NULL CONSTRAINT CHK_NGAYHDNHAP CHECK (NGAYHD <= GETDATE()),
    MANCC VARCHAR(10) NOT NULL CONSTRAINT FK_NHAP_NCC FOREIGN KEY (MANCC) REFERENCES NHA_CUNG_CAP(MANCC),
    MANV VARCHAR(10) NOT NULL CONSTRAINT FK_NHAP_NV FOREIGN KEY (MANV) REFERENCES NHAN_VIEN(MANV)
)

CREATE TABLE CT_NHAP 
(
    MAHDNHAP VARCHAR(20), 
    MAHH VARCHAR(10), 
    DONGIANHAP MONEY NOT NULL CONSTRAINT CHK_DONGIANHAP CHECK (DONGIANHAP > 0),
    SOLUONG INT NOT NULL CONSTRAINT CHK_SOLUONGNHAP CHECK (SOLUONG > 0), 
    THANHTIEN MONEY CONSTRAINT CHK_TTNHAP CHECK (THANHTIEN > 0), 
    CONSTRAINT PK_CT_NHAP PRIMARY KEY (MAHDNHAP, MAHH), 
    CONSTRAINT FK_CT_NHAP_HDNHAP FOREIGN KEY (MAHDNHAP) REFERENCES NHAP(MAHDNHAP), 
    CONSTRAINT FK_CT_NHAP_HH FOREIGN KEY (MAHH) REFERENCES HANG_HOA(MAHH)
)

CREATE TABLE BAN 
(
    MAHDBAN VARCHAR(20) CONSTRAINT PK_BAN PRIMARY KEY, 
    KYHIEU VARCHAR(10) NOT NULL, 
    SOHD INT NOT NULL, 
    CONSTRAINT UQ_KH_SOHD_BAN UNIQUE (SOHD, KYHIEU),
    THUEVAT DECIMAL(5,2) NOT NULL CONSTRAINT CHK_THUEBAN CHECK (THUEVAT BETWEEN 0 AND 10),
    TONGCONG MONEY CONSTRAINT CHK_TONGCONGBAN CHECK (TONGCONG >= 0),
    TONGTIEN MONEY CONSTRAINT CHK_TONGTIENBAN CHECK (TONGTIEN >= 0),
    HTTT VARCHAR(2) CONSTRAINT CHK_HTTTBAN CHECK (HTTT IN ('TM', 'CK')),
    NGAYHD DATETIME NOT NULL CONSTRAINT CHK_NGAYHDBAN CHECK (NGAYHD <= GETDATE()),
    MAKH VARCHAR(10) NOT NULL CONSTRAINT FK_BAN_KH FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MAKH),
    MANV VARCHAR(10) NOT NULL CONSTRAINT FK_BAN_NV FOREIGN KEY (MANV) REFERENCES NHAN_VIEN(MANV)
)

CREATE TABLE CT_BAN 
(
    MAHDBAN VARCHAR(20), 
    MAHH VARCHAR(10), 
    SOLUONG INT NOT NULL CONSTRAINT CHK_SOLUONGBAN CHECK (SOLUONG > 0), 
    THANHTIEN MONEY CONSTRAINT CHK_TTBAN CHECK (THANHTIEN > 0), 
    CONSTRAINT PK_CT_BAN PRIMARY KEY (MAHDBAN, MAHH), 
    CONSTRAINT FK_CT_BAN_HDBAN FOREIGN KEY (MAHDBAN) REFERENCES BAN(MAHDBAN), 
    CONSTRAINT FK_CT_BAN_HH FOREIGN KEY (MAHH) REFERENCES HANG_HOA(MAHH)
)

CREATE TABLE GIA_BAN 
(
    MAGIABAN VARCHAR(20) CONSTRAINT PK_GIA_BAN PRIMARY KEY, 
    MAHH VARCHAR(10) NOT NULL CONSTRAINT FK_GIABAN_HH FOREIGN KEY (MAHH) REFERENCES HANG_HOA(MAHH), 
    GIABANLE MONEY NOT NULL CONSTRAINT CHK_GIABANLE CHECK (GIABANLE > 0), 
    GIABANSI MONEY CONSTRAINT CHK_GIABANSI1 CHECK (GIABANSI > 0), 
	CONSTRAINT CHK_GIABANSI2 CHECK (GIABANSI <= GIABANLE),
    NGAYBATDAU DATETIME NOT NULL,
    NGAYKETTHUC DATETIME NOT NULL,
	CONSTRAINT CHK_NGAYAPDUNG CHECK (NGAYKETTHUC > NGAYBATDAU)
)

CREATE TABLE CONG_NO_NCC 
(
    MACN_NCC VARCHAR(20) CONSTRAINT PK_CONG_NO_NCC PRIMARY KEY, 
    MAHDNHAP VARCHAR(20) NOT NULL CONSTRAINT FK_CNNCC_NHAP FOREIGN KEY (MAHDNHAP) REFERENCES NHAP(MAHDNHAP),
    SOTIENDATRA MONEY NOT NULL DEFAULT 0 CONSTRAINT CHK_DATRANCC CHECK (SOTIENDATRA >= 0),
    HTTT VARCHAR(2) CONSTRAINT CHK_HTTT_NCC CHECK (HTTT IN ('TM', 'CK')),
    NGAYHENTRA DATE NOT NULL,
    NGAYTT DATE CONSTRAINT CHK_NGAYTT_NCC CHECK (NGAYTT <= GETDATE()),
    TRANGTHAI NVARCHAR(30) NOT NULL CONSTRAINT CHK_TRANGTHAI_CNNCC CHECK (TRANGTHAI IN (N'ĐÃ THANH TOÁN HẾT', N'ĐÃ THANH TOÁN MỘT PHẦN', N'CHƯA THANH TOÁN'))
)

CREATE TABLE CONG_NO_KH 
(
    MACN_KH VARCHAR(20) CONSTRAINT PK_CONG_NO_KH PRIMARY KEY, 
    MAHDBAN VARCHAR(20) NOT NULL CONSTRAINT FK_CNKH_BAN FOREIGN KEY (MAHDBAN) REFERENCES BAN(MAHDBAN),
    SOTIENDATRA MONEY NOT NULL DEFAULT 0 CONSTRAINT CHK_KHDATRA CHECK (SOTIENDATRA >= 0),
    HTTT VARCHAR(2) CONSTRAINT CHK_HTTT_CUAKH CHECK (HTTT IN ('TM', 'CK')),
    NGAYHENTRA DATE NOT NULL,
    NGAYTT DATE CONSTRAINT CHK_NGAYTT_CUAKH CHECK (NGAYTT <= GETDATE()),
    TRANGTHAI NVARCHAR(30) NOT NULL CONSTRAINT CHK_TRANGTHAI_CNKH CHECK (TRANGTHAI IN (N'ĐÃ THANH TOÁN HẾT', N'ĐÃ THANH TOÁN MỘT PHẦN', N'CHƯA THANH TOÁN'))
)


